from starlette.applications import Starlette
from starlette.routing import Route

import logging
from pathlib import Path

from starlette.applications import Starlette
from starlette.routing import Route
from starlette.requests import Request
from starlette.responses import JSONResponse

import base64
import json
import os

DOMAIN = os.getenv("domain")

# Note: These get generated by the auth_token.py script
JWKS = json.loads((Path(__file__).parents[1] / "static" / "jwks.json").read_text())


def oauth_authorization_server(request: Request) -> str:
    """Authentication server metadata.

    This JSON contains information about the capabilities of the authentication
    server and what to do to get an access token. You would find this on any
    server that can grant access tokens.

    Note: You can find both `oauth_protected_source` and
    `oauth_authorization_server` in this example because this server hosts both
    the protected resource and the authentication server. In other words, it
    manges its own access tokens.

    """
    return JSONResponse(
        {
            "issuer": f"https://{DOMAIN}",
            "token_endpoint": f"https://{DOMAIN}/token",
            "grant_types_supported": ["client_credentials"],
            "scopes_supported": ["mcp:full_access"],
            "token_endpoint_auth_methods_supported": ["client_secret_basic"],
            "jwks_uri": f"https://{DOMAIN}/.well-known/jwks",
        }
    )


async def get_token(request: Request) -> str:
    """Hand out access tokens to validated clients by issuing a signed JWT."""

    return JSONResponse(
            {
                "error": "invalid_request",
                "error_description": "Tokens are manually issued by the MCP server admin.",
            },
            status_code=400,
        )


def get_jwks(request: Request) -> JSONResponse:
    return JSONResponse(JWKS)


auth_server = Starlette(
    routes=[
        Route("/.well-known/jwks", get_jwks),
        Route("/.well-known/oauth-authorization-server", oauth_authorization_server),
        Route("/token", get_token, methods=["POST"]),
    ],
)
